// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlvypcwcwluhdwuzyryz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsdnlwY3djd2x1aGR3dXp5cnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTk2NzksImV4cCI6MjA3MjU5NTY3OX0.X103qE3Zq86YgDVkDoRG09o23BgjHlc9XB56GDLEO_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});